### ISSUE TITLE
Github Actions are failing

### ISSUE THREAD

**Issue by nathakits** [porames/the-researcher-covid-data#32]
Looks like most of the Github Actions are all failing. 
`get-vaccine-delivery`: IndexError: list index out of range
https://github.com/porames/the-researcher-covid-data/runs/4284380038?check_suite_focus=true

`bot-task-scheduler - get-moh-prompt`: selenium TimeoutException
https://github.com/porames/the-researcher-covid-data/runs/4282943528?check_suite_focus=true

**Comment by nathakits** [comment]
After trying to debug this issue, I think I found the problem. I think the missing title attribute is what is throwing the error.

In line 218 and 323
```python
wait.until(
    EC.element_to_be_clickable((By.XPATH, f"//span[contains(@title,'{dose_to_khem[dose_num]}')]"))
).click()
```

As you can see the span doesn't contain the title attribute and so it can't find the element I think.

![image](https://user-images.githubusercontent.com/17331040/143048476-a6b565fc-67ef-4e5b-8a8f-3f4e7b16fe9f.png)

**Comment by nathakits** [comment]
PR https://github.com/porames/the-researcher-covid-data/pull/35

**Comment by nathakits** [comment]
@noppakorn I still see the scraping still fails sometimes due to this.
```python
time.sleep(1)
wait.until(EC.element_to_be_clickable((By.XPATH, f"//span[@class='glyphicon checkbox']"))).click()
```

Maybe increasing the sleep time would help?
```python
time.sleep(2)
wait.until(EC.element_to_be_clickable((By.XPATH, f"//span[@class='glyphicon checkbox']"))).click()
```

Or update the XPATH to something else?

**Comment by nathakits** [comment]
Actually maybe this is better. Instead of removing the class, set the display style to block instead.

Line 123
```python
wd.execute_script("document.getElementsByClassName('searchHeader')[2].style.display = 'block';")
```

PR https://github.com/porames/the-researcher-covid-data/pull/36

**Comment by noppakorn** [comment]
Okay, merged and running the actions again. Hopefully it works this time. Sorry for the long delay, it's university exams season again.

**Comment by nathakits** [comment]
No worries and good luck on your exams!

**Comment by noppakorn** [comment]
Thanks, seems like actions are still failing. Don't know why the page keep changing all the time. One little change and our code break down.😔
https://github.com/porames/the-researcher-covid-data/actions/runs/1500600106

**Comment by nathakits** [comment]
This error is tricky because sometimes it works and sometimes it doesn't. Maybe a better way to handle this is to check for the element before clicking it.

error
```bash
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <span class="glyphicon checkbox"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

quick pseudo code
```python

if (province_dropdown_is_open and checkbox_exists):
   wait.until(EC.element_to_be_clickable((By.XPATH, f"//span[@class='glyphicon checkbox']"))).click()

```

**Comment by nathakits** [comment]
sleep time PR https://github.com/porames/the-researcher-covid-data/pull/37

**Comment by nathakits** [comment]
@noppakorn moh_prompt Actions finally passed. I think it's good to merge to master.

**Comment by noppakorn** [comment]
I think it's fixed now. Thank you for your contribution!
